# This is a basic workflow to help you get started with Actions
name: rxnorm-publish

on:
  schedule:
    - cron: 0 0 */1 * *
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:        
      - run: cd /tmp

      - uses: actions/setup-java@v3.5.0
        with:
          distribution: "temurin"
          java-version: "18"

      - uses: DeLaGuardo/setup-clojure@9.5
        with:
          cli: 1.11.1.1155
      
      - uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
          submodules: 'recursive'
          
      - name: 'Set environment variable for working directory'
        run: echo "WORKING_DIR_PATH=$(pwd)" >> $GITHUB_ENV

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '418.0.0'

      - name: 'Build service-account.json'
        env:
          FTR_GCP_BUCKET_SERVICE_ACCOUNT: ${{ secrets.FTR_GCP_BUCKET_SERVICE_ACCOUNT }}
        run: echo $FTR_GCP_BUCKET_SERVICE_ACCOUNT > $HOME/service-account.json

      - name: 'Gcloud auth'
        run: gcloud auth activate-service-account --key-file=$HOME/service-account.json

      - name: 'Clone FTR repo'
        run: git clone --recurse-submodules https://github.com/HealthSamurai/ftr.git /tmp/ftr-git-repo
        
      - run: |
          git config --global user.email "hello@health-samurai.io" && \
          git config --global user.name "zen-fhir/rxnorm GH Action—Release"
      
      - run: cd /tmp/ftr-git-repo && make up && cd -
        
      - name: 'Run FTR tests'
        run: cd /tmp/ftr-git-repo && make test
        
      - name: 'Silence all safe.directory warnings (otherwise pushing RXNORM zen package to git fails)'
        run: git config --global --add safe.directory $WORKING_DIR_PATH
      
      - name: 'Publish updated RXNORM FTR and zen package'
        env:
          TG_UPDATES_BOT_TOKEN: ${{ secrets.TG_UPDATES_BOT_TOKEN }}
          TG_FTR_UPDATES_CHAT_ID: ${{ secrets.TG_FTR_UPDATES_CHAT_ID }}
          UMLS_API_KEY: ${{ secrets.UMLS_API_KEY }}
        run: |
          cd /tmp/ftr-git-repo && \
          clojure -X:pipeline ftr.ci-pipelines.rxnorm.core/pipeline \
          :tg-bot-token '"'$TG_UPDATES_BOT_TOKEN'"' \
          :tg-channel-id '"'$TG_FTR_UPDATES_CHAT_ID'"' \
          :api-key '"'$UMLS_API_KEY'"' \
          :gs-object-url '"gs://ftr/rxnorm"' \
          :gs-ftr-object-url '"gs://ftr"' \
          :working-dir-path '"'$WORKING_DIR_PATH'"' \
          :ci-run-url '"https://github.com/'$GITHUB_REPOSITORY'/actions/runs/'$GITHUB_RUN_ID'"'
      - name: 'Fail notifier'
        if: always()
        run: |
              if [[ ${{ job.status }} == 'failure' ]]; then
                echo "Sending notification to Telegram channel"
                curl -X POST "https://api.telegram.org/bot${{ secrets.TG_UPDATES_BOT_TOKEN }}/sendMessage" \
                  -d "chat_id=${{ secrets.TG_FTR_UPDATES_CHAT_ID }}" \
                  -d "parse_mode=HTML" \
                  -d "text=❌ RXNORM pipeline failed prematurely. <a href=\"https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID\">See CI run.</a>"
              fi
